frameworkVersion: "3"

service: ${env:SERVICE_NAME, 'service'}

useDotenv: true
plugins:
  - serverless-iam-roles-per-function

provider:
  name: aws
  region: ${env:AWS_REGION, 'eu-west-1'}
  runtime: go1.x
  stage: ${opt:stage, 'dev'}
  memorySize: 256
  timeout: 29
  environment:
    SERVICE_NAME: ${self:service}
    SERVICE_ENV: ${opt:stage, 'dev'}
    SERVICE_VERSION: ${env:GIT_TAG, 'NO_VERSION'}
    ENTERPRISE_EVENT_BRIDGE: ${env:ENTERPRISE_EVENT_BRIDGE, 'default'}

package:
  individually: true
  exclude:
    - "**/*"

functions:
  - ${file(src/functions/v1-hello-say-hello/function.yml)}


resources:
  - Resources:
      ErrorHandling:
        Type: 'AWS::ApiGateway::GatewayResponse'
        Properties:
          ResponseParameters:
            gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
            gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
          ResponseTemplates:
            application/json: |
              {
                "message": $context.error.messageString,
                "type": "$context.error.responseType",
                "status": 500,
                "path": "$context.resourcePath",
              }
          StatusCode: "500"
          ResponseType: DEFAULT_5XX
          RestApiId:
            Ref: ApiGatewayRestApi
