version: "3"

dotenv: ['.env']

tasks:
  project:build:
    env:
      STAGE: "dev"
      GOARCH: "amd64"
      GOOS: "linux"
    cmds:
      - for dir in ./src/modules/*; do dir=${dir%*/} go build -ldflags="-s -w" -o bin/"${dir##*/}" src/modules/"${dir##*/}"/main.go; done
  project:clean: rm -fr bin
  project:deploy:
    env:
      GIT_TAG:
        sh: git describe --always --tags
    cmds:
      - task: project:build
      - sls deploy --verbose --aws-profile $DEPLOYMENT_PROFILE
      - task: project:clean
  project:destroy:
    cmds:
      - sls remove --verbose --aws-profile $DEPLOYMENT_PROFILE
      - task: project:clean
  project:prepare:
    cmds:
      - npm install && (cd documentation/app-docs && npm install)
      - cd documentation/events-docs && npm install
  docs:generateAll:
    cmds:
      - task: docs:app:generate
      - task: docs:events:generate
  docs:app:generate:
    dir: documentation/app-docs
    cmds:
      - npm run build
  docs:events:generate:
    env:
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
    dir: documentation/events-docs
    cmds:
      - ag api.yml @asyncapi/html-template -o dist --force-write
