name: development
on: pull_request

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: golangci/golangci-lint-action@v3
        with:
          working-directory: "./src"
  staticcheck:
    name: Static Check
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: WillAbides/setup-go-faster@v1.7.0
        with:
          go-version: 1.18.x
      - uses: dominikh/staticcheck-action@v1.2.0
        with:
            version: "2022.1"
            build-tags: "-s -w"
            install-go: false
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: WillAbides/setup-go-faster@v1.7.0
        with:
          go-version: 1.18.x
      - name: Install Task
        uses: arduino/setup-task@v1
      - name: Build
        run: task project:build
  unit:
    name: Unit Tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: WillAbides/setup-go-faster@v1.7.0
        with:
          go-version: 1.18.x
      - name: Install Task
        uses: arduino/setup-task@v1
      - name: Runt tests
        run: task tests:all
  terraform:
    name: Terraform
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Init Terragrunt
        uses: the-commons-project/terragrunt-github-actions@master
        with:
          tf_actions_version: "latest"
          tg_actions_version: "latest"
          tf_actions_subcommand: 'run-all init'
          tf_actions_working_dir: "infrastructure"
          tf_actions_comment: false
      - name: Validate infrastructure
        uses: the-commons-project/terragrunt-github-actions@master
        with:
          tf_actions_version: "latest"
          tg_actions_version: "latest"
          tf_actions_subcommand: 'run-all validate'
          tf_actions_working_dir: "infrastructure"
          tf_actions_comment: false
      - name: Plan infrastructure
        uses: the-commons-project/terragrunt-github-actions@master
        with:
          tf_actions_version: "latest"
          tg_actions_version: "latest"
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: "infrastructure/dev"
          tf_actions_comment: false
  deploy:
    needs:
      - unit
      - staticcheck
      - build
      - lint
    name: Deploy to AWS
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: WillAbides/setup-go-faster@v1.7.0
        with:
          go-version: 1.18.x
      - name: Deploy to AWS
        run: echo "Deployed!"
